// AUTO-GENERATED by scripts/generate-react-wrappers.mjs — do not edit by hand.
// Run `npm run generate:react` to regenerate.
//
// React 18 wrappers around the Assemble Lit custom elements, for consumers
// (such as Figma Make) that need React components instead of raw custom
// elements. Import from '@mcafee-eng/assemble/react'.
import * as React from 'react';
import { createComponent } from '@lit/react';
import * as Elements from './index.js';

// Re-export the design token stylesheet path helper is handled by package exports.

export const AsmAccordionItem = createComponent({
  react: React,
  tagName: 'asm-accordion-item',
  elementClass: Elements.AsmAccordionItem,
  events: {
    onToggle: 'toggle',
  },
});

export const AsmAlertBanner = createComponent({
  react: React,
  tagName: 'asm-alert-banner',
  elementClass: Elements.AsmAlertBanner,
  events: {
    onAction: 'action',
    onClose: 'close',
  },
});

export const AsmBadge = createComponent({
  react: React,
  tagName: 'asm-badge',
  elementClass: Elements.AsmBadge,
});

export const AsmBrand = createComponent({
  react: React,
  tagName: 'asm-brand',
  elementClass: Elements.AsmBrand,
});

export const AsmButton = createComponent({
  react: React,
  tagName: 'asm-button',
  elementClass: Elements.AsmButton,
});

export const AsmCalendar = createComponent({
  react: React,
  tagName: 'asm-calendar',
  elementClass: Elements.AsmCalendar,
  events: {
    onChange: 'change',
    onRangeChange: 'range-change',
    onConfirm: 'confirm',
    onCancel: 'cancel',
    onClear: 'clear',
  },
});

export const AsmCard = createComponent({
  react: React,
  tagName: 'asm-card',
  elementClass: Elements.AsmCard,
  events: {
    onCardClick: 'card-click',
  },
});

export const AsmCarouselIndicator = createComponent({
  react: React,
  tagName: 'asm-carousel-indicator',
  elementClass: Elements.AsmCarouselIndicator,
});

export const AsmChatBubble = createComponent({
  react: React,
  tagName: 'asm-chat-bubble',
  elementClass: Elements.AsmChatBubble,
});

export const AsmCheckbox = createComponent({
  react: React,
  tagName: 'asm-checkbox',
  elementClass: Elements.AsmCheckbox,
  events: {
    onChange: 'change',
  },
});

export const AsmDateInput = createComponent({
  react: React,
  tagName: 'asm-date-input',
  elementClass: Elements.AsmDateInput,
  events: {
    onChange: 'change',
    onRangeChange: 'range-change',
  },
});

export const AsmDivider = createComponent({
  react: React,
  tagName: 'asm-divider',
  elementClass: Elements.AsmDivider,
});

export const AsmEmptyState = createComponent({
  react: React,
  tagName: 'asm-empty-state',
  elementClass: Elements.AsmEmptyState,
});

export const AsmFeedback = createComponent({
  react: React,
  tagName: 'asm-feedback',
  elementClass: Elements.AsmFeedback,
  events: {
    onThumbsUp: 'thumbs-up',
    onThumbsDown: 'thumbs-down',
  },
});

export const AsmIcon = createComponent({
  react: React,
  tagName: 'asm-icon',
  elementClass: Elements.AsmIcon,
});

export const AsmIconButton = createComponent({
  react: React,
  tagName: 'asm-icon-button',
  elementClass: Elements.AsmIconButton,
});

export const AsmListItem = createComponent({
  react: React,
  tagName: 'asm-list-item',
  elementClass: Elements.AsmListItem,
  events: {
    onPress: 'press',
  },
});

export const AsmLoader = createComponent({
  react: React,
  tagName: 'asm-loader',
  elementClass: Elements.AsmLoader,
});

export const AsmMenu = createComponent({
  react: React,
  tagName: 'asm-menu',
  elementClass: Elements.AsmMenu,
});

export const AsmMenuItem = createComponent({
  react: React,
  tagName: 'asm-menu-item',
  elementClass: Elements.AsmMenuItem,
});

export const AsmModal = createComponent({
  react: React,
  tagName: 'asm-modal',
  elementClass: Elements.AsmModal,
  events: {
    onClose: 'close',
  },
});

export const AsmNavDrawer = createComponent({
  react: React,
  tagName: 'asm-nav-drawer',
  elementClass: Elements.AsmNavDrawer,
  events: {
    onItemClick: 'item-click',
  },
});

export const AsmNavListItem = createComponent({
  react: React,
  tagName: 'asm-nav-list-item',
  elementClass: Elements.AsmNavListItem,
});

export const AsmNavSection = createComponent({
  react: React,
  tagName: 'asm-nav-section',
  elementClass: Elements.AsmNavSection,
});

export const AsmNavigationRail = createComponent({
  react: React,
  tagName: 'asm-navigation-rail',
  elementClass: Elements.AsmNavigationRail,
  events: {
    onBrandClick: 'brand-click',
  },
});

export const AsmNavigationRailItem = createComponent({
  react: React,
  tagName: 'asm-navigation-rail-item',
  elementClass: Elements.AsmNavigationRailItem,
  events: {
    onItemClick: 'item-click',
    onToggleStart: 'toggle-start',
    onToggleEnd: 'toggle-end',
  },
});

export const AsmPagination = createComponent({
  react: React,
  tagName: 'asm-pagination',
  elementClass: Elements.AsmPagination,
  events: {
    onPageChange: 'page-change',
  },
});

export const AsmPeekLabel = createComponent({
  react: React,
  tagName: 'asm-peek-label',
  elementClass: Elements.AsmPeekLabel,
});

export const AsmPhoneput = createComponent({
  react: React,
  tagName: 'asm-phoneput',
  elementClass: Elements.AsmPhoneput,
  events: {
    onChange: 'change',
  },
});

export const AsmProgressBar = createComponent({
  react: React,
  tagName: 'asm-progress-bar',
  elementClass: Elements.AsmProgressBar,
});

export const AsmRadio = createComponent({
  react: React,
  tagName: 'asm-radio',
  elementClass: Elements.AsmRadio,
  events: {
    onChange: 'change',
  },
});

export const AsmSideSheet = createComponent({
  react: React,
  tagName: 'asm-side-sheet',
  elementClass: Elements.AsmSideSheet,
});

export const AsmSkeletonLoader = createComponent({
  react: React,
  tagName: 'asm-skeleton-loader',
  elementClass: Elements.AsmSkeletonLoader,
});

export const AsmSnackbar = createComponent({
  react: React,
  tagName: 'asm-snackbar',
  elementClass: Elements.AsmSnackbar,
  events: {
    onAction: 'action',
    onClose: 'close',
  },
});

export const AsmSplitButton = createComponent({
  react: React,
  tagName: 'asm-split-button',
  elementClass: Elements.AsmSplitButton,
  events: {
    onAction: 'action',
    onToggle: 'toggle',
  },
});

export const AsmStatusIndicator = createComponent({
  react: React,
  tagName: 'asm-status-indicator',
  elementClass: Elements.AsmStatusIndicator,
});

export const AsmStatusNotification = createComponent({
  react: React,
  tagName: 'asm-status-notification',
  elementClass: Elements.AsmStatusNotification,
});

export const AsmSwitch = createComponent({
  react: React,
  tagName: 'asm-switch',
  elementClass: Elements.AsmSwitch,
  events: {
    onChange: 'change',
  },
});

export const AsmTab = createComponent({
  react: React,
  tagName: 'asm-tab',
  elementClass: Elements.AsmTab,
  events: {
    onTabSelect: 'tab-select',
  },
});

export const AsmTabGroup = createComponent({
  react: React,
  tagName: 'asm-tab-group',
  elementClass: Elements.AsmTabGroup,
  events: {
    onTabChange: 'tab-change',
  },
});

export const AsmTable = createComponent({
  react: React,
  tagName: 'asm-table',
  elementClass: Elements.AsmTable,
});

export const AsmTag = createComponent({
  react: React,
  tagName: 'asm-tag',
  elementClass: Elements.AsmTag,
  events: {
    onClose: 'close',
  },
});

export const AsmTextField = createComponent({
  react: React,
  tagName: 'asm-text-field',
  elementClass: Elements.AsmTextField,
  events: {
    onInput: 'input',
    onChange: 'change',
  },
});

export const AsmToggleGroup = createComponent({
  react: React,
  tagName: 'asm-toggle-group',
  elementClass: Elements.AsmToggleGroup,
  events: {
    onChange: 'change',
  },
});

export const AsmToggleItem = createComponent({
  react: React,
  tagName: 'asm-toggle-item',
  elementClass: Elements.AsmToggleItem,
});

export const AsmTooltip = createComponent({
  react: React,
  tagName: 'asm-tooltip',
  elementClass: Elements.AsmTooltip,
});

export const AsmTopbar = createComponent({
  react: React,
  tagName: 'asm-topbar',
  elementClass: Elements.AsmTopbar,
  events: {
    onLeftPress: 'left-press',
    onRightPress: 'right-press',
    onPress: 'press',
  },
});

export const AsmTopbarDesktop = createComponent({
  react: React,
  tagName: 'asm-topbar-desktop',
  elementClass: Elements.AsmTopbarDesktop,
});

// Typescale text elements (registered dynamically in components/text/text.ts).
export const AsmDisplayLarge = createComponent({
  react: React,
  tagName: 'asm-display-large',
  elementClass: Elements.AsmTextElements['asm-display-large'],
});

export const AsmDisplayLargeBold = createComponent({
  react: React,
  tagName: 'asm-display-large-bold',
  elementClass: Elements.AsmTextElements['asm-display-large-bold'],
});

export const AsmDisplayMedium = createComponent({
  react: React,
  tagName: 'asm-display-medium',
  elementClass: Elements.AsmTextElements['asm-display-medium'],
});

export const AsmDisplayMediumBold = createComponent({
  react: React,
  tagName: 'asm-display-medium-bold',
  elementClass: Elements.AsmTextElements['asm-display-medium-bold'],
});

export const AsmDisplaySmall = createComponent({
  react: React,
  tagName: 'asm-display-small',
  elementClass: Elements.AsmTextElements['asm-display-small'],
});

export const AsmDisplaySmallBold = createComponent({
  react: React,
  tagName: 'asm-display-small-bold',
  elementClass: Elements.AsmTextElements['asm-display-small-bold'],
});

export const AsmHeadlineLarge = createComponent({
  react: React,
  tagName: 'asm-headline-large',
  elementClass: Elements.AsmTextElements['asm-headline-large'],
});

export const AsmHeadlineLargeBold = createComponent({
  react: React,
  tagName: 'asm-headline-large-bold',
  elementClass: Elements.AsmTextElements['asm-headline-large-bold'],
});

export const AsmHeadlineMedium = createComponent({
  react: React,
  tagName: 'asm-headline-medium',
  elementClass: Elements.AsmTextElements['asm-headline-medium'],
});

export const AsmHeadlineMediumBold = createComponent({
  react: React,
  tagName: 'asm-headline-medium-bold',
  elementClass: Elements.AsmTextElements['asm-headline-medium-bold'],
});

export const AsmHeadlineSmall = createComponent({
  react: React,
  tagName: 'asm-headline-small',
  elementClass: Elements.AsmTextElements['asm-headline-small'],
});

export const AsmHeadlineSmallBold = createComponent({
  react: React,
  tagName: 'asm-headline-small-bold',
  elementClass: Elements.AsmTextElements['asm-headline-small-bold'],
});

export const AsmTitleLarge = createComponent({
  react: React,
  tagName: 'asm-title-large',
  elementClass: Elements.AsmTextElements['asm-title-large'],
});

export const AsmTitleLargeBold = createComponent({
  react: React,
  tagName: 'asm-title-large-bold',
  elementClass: Elements.AsmTextElements['asm-title-large-bold'],
});

export const AsmTitleMedium = createComponent({
  react: React,
  tagName: 'asm-title-medium',
  elementClass: Elements.AsmTextElements['asm-title-medium'],
});

export const AsmTitleMediumBold = createComponent({
  react: React,
  tagName: 'asm-title-medium-bold',
  elementClass: Elements.AsmTextElements['asm-title-medium-bold'],
});

export const AsmTitleSmall = createComponent({
  react: React,
  tagName: 'asm-title-small',
  elementClass: Elements.AsmTextElements['asm-title-small'],
});

export const AsmTitleSmallBold = createComponent({
  react: React,
  tagName: 'asm-title-small-bold',
  elementClass: Elements.AsmTextElements['asm-title-small-bold'],
});

export const AsmBodyLarge = createComponent({
  react: React,
  tagName: 'asm-body-large',
  elementClass: Elements.AsmTextElements['asm-body-large'],
});

export const AsmBodyLargeBold = createComponent({
  react: React,
  tagName: 'asm-body-large-bold',
  elementClass: Elements.AsmTextElements['asm-body-large-bold'],
});

export const AsmBodyMedium = createComponent({
  react: React,
  tagName: 'asm-body-medium',
  elementClass: Elements.AsmTextElements['asm-body-medium'],
});

export const AsmBodyMediumBold = createComponent({
  react: React,
  tagName: 'asm-body-medium-bold',
  elementClass: Elements.AsmTextElements['asm-body-medium-bold'],
});

export const AsmBodySmall = createComponent({
  react: React,
  tagName: 'asm-body-small',
  elementClass: Elements.AsmTextElements['asm-body-small'],
});

export const AsmBodySmallBold = createComponent({
  react: React,
  tagName: 'asm-body-small-bold',
  elementClass: Elements.AsmTextElements['asm-body-small-bold'],
});

export const AsmLabelLarge = createComponent({
  react: React,
  tagName: 'asm-label-large',
  elementClass: Elements.AsmTextElements['asm-label-large'],
});

export const AsmLabelLargeBold = createComponent({
  react: React,
  tagName: 'asm-label-large-bold',
  elementClass: Elements.AsmTextElements['asm-label-large-bold'],
});

export const AsmLabelMedium = createComponent({
  react: React,
  tagName: 'asm-label-medium',
  elementClass: Elements.AsmTextElements['asm-label-medium'],
});

export const AsmLabelMediumBold = createComponent({
  react: React,
  tagName: 'asm-label-medium-bold',
  elementClass: Elements.AsmTextElements['asm-label-medium-bold'],
});

export const AsmLabelSmall = createComponent({
  react: React,
  tagName: 'asm-label-small',
  elementClass: Elements.AsmTextElements['asm-label-small'],
});

export const AsmLabelSmallBold = createComponent({
  react: React,
  tagName: 'asm-label-small-bold',
  elementClass: Elements.AsmTextElements['asm-label-small-bold'],
});
